### ISSUE TITLE
Memory -> Stomp -> Edit sysex

### ISSUE THREAD

**Issue by tdroxler** [Colatino/PicoZoom#3]
Hi,

I'm starting to play with my G1X four (I'm better at coding that playing guitar, so I need an excuse not to practice my scales :stuck_out_tongue_closed_eyes: )

You did an amazing job here.

Do you know by any chance the `sysex` code to switch between the `Memory -> Stomp -> Edit` modes?

Thx a lot,

Cheers

**Comment by Colatino** [comment]
There isn't a documented sysex to cycle through screens... I've discussed this matter with the guys that cracked the communications protocol and they also didn't find one.

You could change the board by soldering a momentary pushbutton to the terminals of the one that does the cycling.. but no coding there...

**Comment by tdroxler** [comment]
Thx for your answer.

I take the opportunity for another question then. From what I found playing with wireshark and on some other resources on internet, there are some sysex to change to specific patches, but do we have a way to select any of the patches, the same way you nicely toggle the effect here?
https://github.com/Colatino/PicoZoom/blob/45fa947c4a9f63ee26ab7b70de7b5f0f8d13f39b/src/beta/beta.ino#L409-L410

**Comment by tdroxler** [comment]
actually from [this video](https://www.youtube.com/watch?v=jKNqQNcffFs) I could easily find them all

```sh
#/bin/sh
for bank in {0..4}
do
  for patch in {0..9}
  do
    echo "f0b00000b0200${bank}c000f7f0cc0${patch}f7"
  done
done
```

Thx again for your amazing work, this helped me a lot to understand this all midi/sysex world.
