### ISSUE TITLE
Compilation fatal error: pico/stdio.h: No such file or directory

### ISSUE THREAD

**Issue by ojungleboy** [Colatino/PicoZoom#4]
Hi, I am pretty sure this is a newbie/environment related problem as this is my first time using Pico and Raspberry. I have several projects in ESP32.

The following error is happening when  compiling the code:

In file included from e:\Users\Jungle Boy\Documents\Arduino\libraries\Pico_PIO_USB\src\pio_usb.c:17:0:
C:\Users\Jungle Boy\AppData\Local\Arduino15\packages\arduino\hardware\mbed_rp2040\4.0.2\cores\arduino/mbed/targets/TARGET_RASPBERRYPI/TARGET_RP2040/pico-sdk/common/pico_stdlib/include/pico/stdlib.h:11:10: fatal error: pico/stdio.h: No such file or directory
 #include "pico/stdio.h"
 
 I already tried to reinstal SDK but no luck. Anyone can please give me some light??

Thanks

**Comment by Colatino** [comment]
Are you using [this one](https://github.com/earlephilhower/arduino-pico)?

This project doesn't use the official Arduino installation (the mbed one)

Installin through the Arduino IDE you'll have to choose this one
![image](https://user-images.githubusercontent.com/80787901/231915052-b09f457c-8e42-4a36-bcb9-4dab5a142ac2.png)

**Comment by ojungleboy** [comment]
Thanks for your answer. I tried both one and it does a similar problem on the stdio and stdlib libraries

**Comment by ojungleboy** [comment]
I tried several board and this was the last one I choose. But it keep the same error on both boards as I mentioned

**Comment by ojungleboy** [comment]
I reinstalled the environment and it seems that the error regarding the Adafruit Tiny USBLibrary. It looks that the custom library is conflicting with the RP2040 one.

Any idea how to solve it? Thanks!

> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino: In function 'void poll_midi_host_rx()':
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino:771:10: error: 'tuh_midi_configured' was not declared in this scope; did you mean 'tuh_configure'?
>   771 |     if (!tuh_midi_configured(midi_dev_addr)) {
>       |          ^~~~~~~~~~~~~~~~~~~
>       |          tuh_configure
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino:777:9: error: 'tuh_midih_get_num_rx_cables' was not declared in this scope
>   777 |     if (tuh_midih_get_num_rx_cables(midi_dev_addr) < 1) {
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino:781:5: error: 'tuh_midi_read_poll' was not declared in this scope; did you mean 'tud_midi_read'?
>   781 |     tuh_midi_read_poll(midi_dev_addr);
>       |     ^~~~~~~~~~~~~~~~~~
>       |     tud_midi_read
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino: In function 'void midi_host_task()':
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino:790:5: error: 'tuh_midi_stream_flush' was not declared in this scope; did you mean 'tud_midi_stream_write'?
>   790 |     tuh_midi_stream_flush(midi_dev_addr);
>       |     ^~~~~~~~~~~~~~~~~~~~~
>       |     tud_midi_stream_write
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino: In function 'void send_sysex(uint8_t*, int)':
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino:878:5: error: 'tuh_midi_packet_write' was not declared in this scope; did you mean 'tud_midi_packet_write'?
>   878 |     tuh_midi_packet_write(midi_dev_addr, packet);
>       |     ^~~~~~~~~~~~~~~~~~~~~
>       |     tud_midi_packet_write
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino: In function 'void tuh_midi_rx_cb(uint8_t, uint32_t)':
> E:\Users\Jungle Boy\Documents\Arduino\libraries\PicoZoom-main\src\beta\beta.ino:930:11: error: 'tuh_midi_packet_read' was not declared in this scope; did you mean 'tud_midi_packet_read'?
>   930 |       if (tuh_midi_packet_read(dev_addr, packet)) {
>       |           ^~~~~~~~~~~~~~~~~~~~
>       |           tud_midi_packet_read
> Multiple libraries were found for "Adafruit_TinyUSB.h"
>   Used: E:\Users\Jungle Boy\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master
>   Not used: C:\Users\Jungle Boy\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\Adafruit_TinyUSB_Arduino
> Using library MIDI Library at version 5.0.2 in folder: E:\Users\Jungle Boy\Documents\Arduino\libraries\MIDI_Library 
> Using library Pico PIO USB at version 0.5.2 in folder: E:\Users\Jungle Boy\Documents\Arduino\libraries\Pico_PIO_USB 
> Using library Adafruit TinyUSB Library at version 2.0.3 in folder: E:\Users\Jungle Boy\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master 
> Using library Adafruit GFX Library at version 1.11.5 in folder: E:\Users\Jungle Boy\Documents\Arduino\libraries\Adafruit_GFX_Library 
> Using library Adafruit BusIO at version 1.14.1 in folder: E:\Users\Jungle Boy\Documents\Arduino\libraries\Adafruit_BusIO 
> Using library Wire at version 1.0 in folder: C:\Users\Jungle Boy\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\Wire 
> Using library SPI at version 1.0 in folder: C:\Users\Jungle Boy\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.1.1\libraries\SPI 
> Using library Adafruit SSD1306 at version 2.5.7 in folder: E:\Users\Jungle Boy\Documents\Arduino\libraries\Adafruit_SSD1306 
> exit status 1
> 
> Compilation error: 'tuh_midi_configured' was not declared in this scope; did you mean 'tuh_configure'?
>

**Comment by ojungleboy** [comment]
A wise man told me to use the search and I realized that I had the same isse as issue #1 

Now it is compiling and thank you once again!
