### ISSUE TITLE
error: redefinition of 'static uint8_t Adafruit_USBD_CDC::getInstanceCount()'

### ISSUE THREAD

**Issue by ThiagoMux** [Colatino/PicoZoom#8]
@Colatino, 

Em primeiro lugar obrigado por compartilhar o trabalho!!

Te escrevo pois ao tentar verificar/compilar o código estou recebendo um erro de múltiplas definições de um parâmetro. Como não conheço nada de programação e é minha primeira experiência com Arduíno imagino que possa ser algo mais simples do que parece.

c:\Users\Desktop\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\arduino\Adafruit_USBD_CDC.cpp:50:9: error: redefinition of 'static uint8_t Adafruit_USBD_CDC::getInstanceCount()'
   50 | uint8_t Adafruit_USBD_CDC::getInstanceCount(void) { return _instance_count; }
      |         ^~~~~~~~~~~~~~~~~
In file included from C:\Users\Desktop\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.7.2\cores\rp2040/Arduino.h:115,
                 from c:\Users\Desktop\Documents\Arduino\libraries\Adafruit_TinyUSB_Library\src\arduino\Adafruit_USBD_CDC.cpp:29:
C:\Users\Desktop\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.7.2/libraries/Adafruit_TinyUSB_Arduino/src/arduino/Adafruit_USBD_CDC.h:46:18: note: 'static uint8_t Adafruit_USBD_CDC::getInstanceCount()' previously defined here
   46 |   static uint8_t getInstanceCount(void) { return _instance_count; }
      |                  ^~~~~~~~~~~~~~~~
Multiple libraries were found for "Adafruit_TinyUSB.h"
  Used: C:\Users\Desktop\Documents\Arduino\libraries\Adafruit_TinyUSB_Library
  Not used: C:\Users\Desktop\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.7.2\libraries\Adafruit_TinyUSB_Arduino
exit status 1

Compilation error: exit status 1

Passos realizados
- instalação do Arduino IDE
- ativação da placa PI PICO (VCC-GND YD RP2040) e seleção da frequência para 120 MHz e USB
- Instalação da bibliotecas
- substituição da biblioteca TinyUSB pela do arquivo (desinstalação da mais atual e inclusão via arquivo zip no Arduino IDE)
- abri o arquivo "Beta.ino" no Arduíno IDE e pedi para compilar

Em tempo, eu consigo conectar o PI PICO via USB e fazer os exemplos de piscar o LED

Consegue me dar uma orientação?

Obrigado,

Thiago

**Comment by Colatino** [comment]
@ThiagoMux 

Esse problema também foi relatado na #6 . Quando eu adaptei a biblioteca Adafruit TinyUSB, a original (que está incluída no core Arduino-Pico) ainda não tinha algumas das funções que precisei criar. Essa ```getInstanceCount``` é uma delas. Um outro ponto é a versão do core Arduino-Pico, que quando criei estava em algo como 2.4 e agora já passa da 3.7.

Talvez seja necessário readaptar as bibliotecas novamente e não estou tendo tempo livre o suficiente para isso no momento.

Minha sugestão seria fazer um downgrade da Arduino-Pico para uma versão próxima da 2.5 ou 2.7 e testar compilar novamente, pode ser que funcione.

**Comment by ThiagoMux** [comment]
@Colatino ,

Obrigado pela resposta....fir o downgrade pra versão 2.50 e agora compilou sem erros.

Valeu e grande abraço!
